### ISSUE TITLE
Dll access denied in Cutting stock problem

### ISSUE THREAD

**Issue by delfador** [aimms/examples#1]
When I run the cutting stock model, I get access denied errors when the procedures try to call any of the two dll in the project. I am running AIMMS 4.1 (64bit)

Furthermore, the GMP approach does not create any new cutting patterns in addition to the initial set.

**Comment by MarcelHunting** [comment]
The GMP issue has been fixed. The coefficients in GMP::Coefficient::Set used the wrong sign for the objective; this was functionality changed in AIMMS 4.

The DLL errors I could not reproduce. I used AIMMS 4.2 (64 bit).

**Comment by delfador** [comment]
Thanks for solving the problem. It turns out that my user account didn't have execution rights for the DLL files. After I changed that, the problems were solved.
