### ISSUE TITLE
Data reconciliation: range error on element parameter while reading NH3.txt with LoadNH3Example

### ISSUE THREAD

**Issue by pchtsp** [aimms/examples#2]
I'm getting the following error while trying to open the application ```Data Reconciliation```:

    The value 'Mixer' is outside the range domain set "NetworkNodes" of element parameter "SourceNode", see also the option "warning range violation".
    
If I add a couple elements to a given set, I get it to read ok (I've added the second line to the ```LoadNH3Example``` procedure):

    empty DataReconciliationModel;

    IntermediateNodes+=data{Mixer, Reactor};

    read from file "<prj>:NH3.txt";

    update DataReconciliationModel;
    
    
I'm using the following:

* Windows 10 64 bits.
* AIMMS 4.27.5766 64 bits.

**Comment by MarcelHunting** [comment]
I removed the statement for SourceNode from the input file and pushed an updated version of the project which should fix this error.
